Improve README.md
AMereBagatelle/fabricskyboxes pull request #41
Opened 2022-05-10 15:31 UTC by RaptaG

I did my best!

2022-05-12 02:42 UTC, AMereBagatelle requested changes
Looks pretty good in general, just a few grammatical fixes and a few notes.  Thanks for submitting the PR!

2022-05-12 02:42 UTC, AMereBagatelle commented on README.md
> +This mod allows the specification of Custom Skyboxes, with any textures that you may want, even with the ones which are already in Minecraft's resources!
Probably just remove the bit after the second comma, it doesn't contribute much and isn't helpful information (I don't even know why I thought it was)

2022-05-12 02:42 UTC, AMereBagatelle commented on README.md
> +### FabricSkyboxes' format
It is grammatically correct but doesn't end up looking that nice in my opinion, possibly `FSB Skybox Format` or similar?  (get rid of the possessive I think)

2022-05-12 02:42 UTC, AMereBagatelle commented on README.md
> +It is **out of the scope** of this mod to support the OptiFine's format. [MCPP++](https://github.com/supsm/MCPPPP) can be used to get this packs to work and you can read its [instructions](https://gi
`the Optifine's` -> `Optifine's`
`this packs` -> `Optifine skyboxes`

2022-05-13 20:39 UTC, RaptaG commented
> Looks pretty good in general, just a few grammatical fixes and a few notes.  Thanks for submitting the PR!

(Forgot to mention) I applied all the changes you requested!

2022-06-08 12:23 UTC, AMereBagatelle approved these changes

2022-06-08 12:33 UTC, merged