Fix skybox visibility in certain situations
AMereBagatelle/fabricskyboxes pull request #45
Opened 2022-06-20 18:41 UTC by heymanMC

- Don't show skybox underwater (vanilla behavior)
- Don't show skybox when player has darkness effect

2022-07-22 12:01 UTC, AMereBagatelle requested changes
Makes sense, however #44 already fixed the darkness issue.

2022-07-22 12:01 UTC, AMereBagatelle commented on src/main/java/io/github/amerebagatelle/fabricskyboxes/skyboxes/AbstractSkybox.java
> +        if (camera.getFocusedEntity() instanceof LivingEntity livingEntity && livingEntity.hasStatusEffect(StatusEffects.DARKNESS))
This change was superseded by #44.

2022-07-22 12:59 UTC, RaptaG commented
> Don't show skybox underwater (vanilla behavior)

Can this be toggleable?

2022-10-23 19:39 UTC, heymanMC commented
Will redo PR with only the underwater change.

2022-10-23 19:39 UTC, closed without merging